export enum GameAction {
  AddToPot = 'AddToPot',
  Deal = 'Deal',
  EndGame = 'EndGame',
  EndGameTrap = 'EndGameTrap',
  EvaluateGame = 'EvaluateGame',
  IncrementRound = 'IncrementRound',
  IncrementTurn = 'IncrementTurn',
  NewGame = 'NewGame',
  NewRound = 'NewRound',
  ResetGame = 'ResetGame',
  SetControllingPlayer = 'SetControllingPlayer',
  SetGameStatus = 'SetGameStatus',
  SetLoser = 'SetLoser',
  SetMinimumBet = 'SetMinimumBet',
  SetSpinnerVisible = 'SetSpinnerVisible',
  SetWinner = 'SetWinner',
  ShowMessageBar = 'ShowMessageBar',
  Stay = 'Stay',
}