import keyMirror from "keymirror";

export default keyMirror({
  /* Game */
  GAME_NEWGAME: null,
  GAME_NEWPLAYER: null,
  GAME_EVALUATEHAND: null,
  GAME_EVALUATEGAME: null,
  GAME_GETPLAYERBYID: null,
  GAME_GETHIGHESTHANDVALUE: null,
  GAME_PAYOUT: null,
  GAME_EVALUATEPLAYERS: null,
  GAME_RESET: null,
  GAME_NEWROUND: null,
  GAME_REMOVESELECTEDFROMPLAYERHAND: null,

  /* Deck */
  DECK_NEWDECK: null,
  DECK_DRAW: null,
  DECK_DRAWRANDOM: null,
  DECK_DRAWFROMBOTTOMOFDECK: null,
  DECK_RESET: null,
  DECK_SHUFFLE: null,
  DECK_PUTONBOTTOMOFDECK: null,
  DECK_PUTONTOPOFDECK: null,
  DECK_REMOVESELECTEDFROMDRAWN: null,

  /* ControlPanel */
  CONTROLPANEL_HIDEOPTIONSPANEL: null,
  CONTROLPANEL_SHOWOPTIONSPANEL: null,
  CONTROLPANEL_SHOWMESSAGEBAR: null,
  CONTROLPANEL_TOGGLEDECKVISIBILITY: null,
  CONTROLPANEL_TOGGLEDRAWNVISIBILITY: null,
  CONTROLPANEL_TOGGLESELECTEDVISIBLITY: null
});
